export const EMAIL = "hi@wblz.xyz"
export const DISCORD = "wblazej#0854"
export const GITHUB = "https://github.com/wblazej"
export const STACKOVERFLOW = "https://stackoverflow.com/users/13574070"
export const TWITTER = "https://twitter.com/wblazej_"
export const GOOGLE_CLOUD = "https://www.cloudskillsboost.google/public_profiles/462083fe-41bc-4543-84db-1b0c42698c09"
export const REPO = "https://github.com/wblazej/personal-website"
export const GET_AGE_REQUEST = "https://serverless.wblz.xyz/get-age/"
