export const EMAIL = "blazej.wrzosok@gmail.com"
export const DISCORD = "wblazej#6957"
export const GITHUB = "https://github.com/wblazej"
export const STACKOVERFLOW = "https://stackoverflow.com/users/13574070"
export const TWITTER = "https://twitter.com/wblazej_"
export const GOOGLE_CLOUD = "https://www.cloudskillsboost.google/public_profiles/462083fe-41bc-4543-84db-1b0c42698c09"
export const REPO = "https://github.com/wblazej/personal-website"
export const GET_AGE_REQUEST = "https://europe-central2-blazej.cloudfunctions.net/get-age"
